### ISSUE TITLE
Table padding left

### ISSUE THREAD

**Issue by cupcakearmy** [IBM/carbon-components-svelte#479]
Hi there, first off thanks for the amazing project, i'm really loving it rn ❤️ 

There is a small issue with tables inside of other tables.
The table inside the [expendable](https://carbon-svelte.vercel.app/components/DataTable#expandable) inherits the padding left from the expandable.

![Bug](https://user-images.githubusercontent.com/14948823/103666768-558cf080-4f75-11eb-90ea-8e2143878155.png)

**Comment by metonym** [comment]
I'd recommend overriding the properties with custom CSS.

**Comment by cupcakearmy** [comment]
Yes, that's what I've done for now.

```css
.wrapper :global(th) {
	padding: 0 !important;
}

.wrapper :global(td) {
	padding-left: var(--cds-spacing-05, 1rem) !important;
}
```

Just wanted to report it in case this is treated as a bug :)
Feel free to close if you think this is an edge case
