### ISSUE TITLE
width and alignment of columns in DataTable

### ISSUE THREAD

**Issue by DemiusAcademius** [IBM/carbon-components-svelte#527]
I have not found an easy way to adjust the column width and alignment in DataTable. Although I researched all the documentation and sources. It would be great to add classes with a key to the columns.

**Comment by DemiusAcademius** [comment]
Thanks for your great work!
Svelte is awesome and Carbon too.

**Comment by metonym** [comment]
You'll need to apply your own custom CSS.

You can try targeting specific columns like so:

```css
// target a column in the datatable head
:global(thead tr th:nth-child(2)) {
  min-width: 6rem;
}

// target a column in the datatable body
:global(tbody tr th:nth-child(2)) {
  min-width: 6rem;
}
```
