### ISSUE TITLE
"Show more" doesn't work for CodeSnippets anymore

### ISSUE THREAD

**Issue by tommy4st** [IBM/carbon-components-svelte#656]
With the current version (0.33) the "Show more" button for the CodeSnippet component only adds a small padding to the bottom. The visible code is not truncated in the first place. See: https://carbon-svelte.vercel.app/components/CodeSnippet

An example, where this is still working, is here: https://carbon-components-svelte-git-fix-code-snippet-carbon-svelte.vercel.app/components/CodeSnippet

If I add the following to the style it works as in the working example:
```css
  :global(.bx--snippet--multi .bx--snippet-container) {
    min-height: 3.5rem;
    max-height: 14.875rem;
    overflow: hidden;
  }
  :global(.bx--snippet--multi.bx--snippet--expand .bx--snippet-container) {
    max-height: 100%;
  }
```
