### ISSUE TITLE
Pagination popups may need explicit background

### ISSUE THREAD

**Issue by brunnerh** [IBM/carbon-components-svelte#712]
Without hover the `<select>` has no background, leading to this for the dark themes on Chrome:

![image](https://user-images.githubusercontent.com/834235/123943031-019b1b80-d99c-11eb-944f-fb4f773dfd1f.png)

It works on Firefox but i do not know where that color is from:

![image](https://user-images.githubusercontent.com/834235/123943544-8d14ac80-d99c-11eb-9ab0-d597ab79d4f2.png)

The `<Select>` component always has a default background which prevents the problem altogether:
```css
.bx--select-input {
    ...
    background-color: var(--cds-field,#f4f4f4);
    ...
}
```
